import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="RNAFlowX | Downloads",
    layout="wide"
)

# ============================================================
# PATHS
# ============================================================

APP_ROOT = Path(__file__).resolve().parents[1]

DATA_ROOT = APP_ROOT / "data"
DOWNLOADS_DIR = DATA_ROOT / "downloads"
REPORTS_DIR = DATA_ROOT / "reports"
BENCHMARK_DIR = DATA_ROOT / "benchmark"

# ============================================================
# CSS
# ============================================================

st.markdown("""
<style>

.download-hero{
    padding:46px;
    border-radius:26px;
    background:linear-gradient(135deg,#062A67 0%,#0E56D8 100%);
    color:white;
    box-shadow:0 18px 36px rgba(15,74,180,.20);
    margin-bottom:30px;
}

.download-hero h1{
    margin:0 0 12px;
    font-size:48px;
    font-weight:800;
}

.download-hero h3{
    margin:0 0 18px;
    color:#75E6FF;
    font-size:22px;
}

.download-hero p{
    max-width:900px;
    color:#E8F3FF;
    font-size:16px;
    line-height:1.8;
}

.section-title{
    margin:34px 0 16px;
    font-size:30px;
    font-weight:800;
    color:#153F73;
}

.download-card{
    background:white;
    border-radius:18px;
    padding:22px;
    box-shadow:0 7px 20px rgba(15,23,42,.07);
    border-top:5px solid #2563EB;
    min-height:155px;
}

.download-card h3{
    color:#153F73;
    margin-bottom:10px;
    font-size:21px;
}

.download-card p{
    color:#64748B;
    line-height:1.6;
    font-size:15px;
}

.status-ok{
    color:#15803D;
    font-weight:700;
    margin:8px 0;
}

.status-missing{
    color:#DC2626;
    font-weight:700;
    margin:8px 0;
}

.report-box{
    padding:24px;
    background:#F8FAFC;
    border:1px solid #E2E8F0;
    border-radius:18px;
    margin-bottom:18px;
}

.report-box h3{
    color:#153F73;
    margin-top:0;
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# HELPERS
# ============================================================

def render_download_card(title, description, file_path, mime, key):
    st.markdown(
        f"""
        <div class="download-card">
            <h3>{title}</h3>
            <p>{description}</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    if file_path.exists():

        st.markdown(
            '<div class="status-ok">✓ Available</div>',
            unsafe_allow_html=True
        )

        data = file_path.read_bytes()

        st.download_button(
            label=f"Download {title}",
            data=data,
            file_name=file_path.name,
            mime=mime,
            width="stretch",
            key=key
        )

    else:

        st.markdown(
            '<div class="status-missing">✗ File not found</div>',
            unsafe_allow_html=True
        )


# ============================================================
# HERO
# ============================================================

st.markdown("""
<div class="download-hero">

<h1>Downloads & Scientific Reports</h1>

<h3>
Analysis Outputs • Reports • Benchmarking • Reproducibility
</h3>

<p>
Access the principal analytical outputs generated by RNAFlowX.
The files below provide reusable differential-expression,
functional-enrichment, quality-control and benchmarking results
for independent inspection and downstream analysis.
</p>

</div>
""", unsafe_allow_html=True)


# ============================================================
# DIFFERENTIAL EXPRESSION
# ============================================================

st.markdown(
    '<div class="section-title">🧬 Differential Expression</div>',
    unsafe_allow_html=True
)

c1, c2, c3 = st.columns(3, gap="large")

with c1:
    render_download_card(
        "Differential Expression",
        "Complete DESeq2 result table containing expression statistics for all tested genes.",
        DOWNLOADS_DIR / "differential_expression.csv",
        "text/csv",
        "de_all"
    )

with c2:
    render_download_card(
        "Significant Genes",
        "Filtered set of statistically significant differentially expressed genes.",
        DOWNLOADS_DIR / "significant_genes.csv",
        "text/csv",
        "de_sig"
    )

with c3:
    render_download_card(
        "Normalized Counts",
        "DESeq2-normalized gene-expression matrix across all biological samples.",
        DOWNLOADS_DIR / "normalized_counts.csv",
        "text/csv",
        "de_norm"
    )


# ============================================================
# QUANTIFICATION
# ============================================================

st.markdown(
    '<div class="section-title">📊 Quantification</div>',
    unsafe_allow_html=True
)

q1, q2 = st.columns(2, gap="large")

with q1:
    render_download_card(
        "Count Matrix",
        "Gene-level count matrix generated through Salmon and tximport.",
        DOWNLOADS_DIR / "count_matrix.csv",
        "text/csv",
        "count_matrix"
    )

with q2:
    render_download_card(
        "TxImport Summary",
        "Summary generated during transcript-to-gene count aggregation.",
        DOWNLOADS_DIR / "tximport_summary.txt",
        "text/plain",
        "tximport_summary"
    )


# ============================================================
# FUNCTIONAL ENRICHMENT
# ============================================================

st.markdown(
    '<div class="section-title">🔬 Functional Enrichment</div>',
    unsafe_allow_html=True
)

e1, e2, e3 = st.columns(3, gap="large")

with e1:
    render_download_card(
        "GO Biological Process",
        "GO Biological Process enrichment results for all significant genes.",
        DOWNLOADS_DIR / "go_bp_all.csv",
        "text/csv",
        "go_bp"
    )

with e2:
    render_download_card(
        "KEGG Pathways",
        "KEGG pathway enrichment results for all significant genes.",
        DOWNLOADS_DIR / "kegg_all.csv",
        "text/csv",
        "kegg"
    )

with e3:
    render_download_card(
        "GSEA Results",
        "Gene Set Enrichment Analysis results using GO Biological Process gene sets.",
        DOWNLOADS_DIR / "gsea_go_bp.csv",
        "text/csv",
        "gsea"
    )


# ============================================================
# ANALYSIS SUMMARIES
# ============================================================

st.markdown(
    '<div class="section-title">📄 Analysis Summaries</div>',
    unsafe_allow_html=True
)

s1, s2 = st.columns(2, gap="large")

with s1:
    render_download_card(
        "DESeq2 Summary",
        "Text summary describing the completed differential-expression analysis.",
        DOWNLOADS_DIR / "deseq2_summary.txt",
        "text/plain",
        "deseq_summary"
    )

with s2:
    render_download_card(
        "Enrichment Summary",
        "Summary describing GO, KEGG and GSEA enrichment analyses.",
        DOWNLOADS_DIR / "enrichment_summary.txt",
        "text/plain",
        "enrichment_summary"
    )


# ============================================================
# MULTIQC
# ============================================================

st.markdown(
    '<div class="section-title">🧪 Quality Control Report</div>',
    unsafe_allow_html=True
)

multiqc_file = REPORTS_DIR / "multiqc_report.html"

if multiqc_file.exists():

    st.markdown("""
<div class="report-box">
    <h3>RNAFlowX MultiQC Report</h3>
    <p>
    Complete MultiQC quality-control report generated directly from the
    RNAFlowX pipeline. Download the interactive HTML report below.
    Key quality metrics are visualized interactively in the Quality Control
    dashboard.
    </p>
</div>
""", unsafe_allow_html=True)

    st.download_button(
        label="Download MultiQC HTML Report",
        data=multiqc_file.read_bytes(),
        file_name="RNAFlowX_MultiQC_Report.html",
        mime="text/html",
        width="stretch",
        key="multiqc_download"
    )

else:

    st.error(
        "MultiQC report is not available in the deployment package."
    )


# ============================================================
# BENCHMARKING
# ============================================================

st.markdown(
    '<div class="section-title">⚡ Performance Benchmark</div>',
    unsafe_allow_html=True
)

b1, b2 = st.columns(2, gap="large")

with b1:
    render_download_card(
        "Benchmark Summary",
        "Workflow-level benchmark summary including task completion and execution statistics.",
        BENCHMARK_DIR / "benchmark_summary.csv",
        "text/csv",
        "benchmark_summary"
    )

with b2:
    render_download_card(
        "Process Metrics",
        "Per-process runtime, CPU, memory and I/O measurements collected from the benchmark execution.",
        BENCHMARK_DIR / "process_metrics.csv",
        "text/csv",
        "process_metrics"
    )


# ============================================================
# DEPLOYMENT NOTE
# ============================================================

st.write("")

st.caption(
    "The public RNAFlowX dashboard uses a lightweight deployment package "
    "containing curated analytical outputs. Large raw sequencing files, "
    "workflow work directories and intermediate quantification artifacts "
    "are intentionally excluded from the web deployment."
)
